POST http://localhost:3001/api/customers
content-type: application/json

{
        "firstname": "Teijo",
        "lastname": "Testinen",
        "email": "Teijo@esim.com",
        "telephone": "45678765",
        "department": "osasto 2"
}